spring:
  application:
    name: worst-movie-api
  datasource:
    url: jdbc:h2:mem:moviesdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE;AUTO_RECONNECT=TRUE;NON_KEYWORDS=year
    username: sa
    password: ''
    driver-class-name: 'org.h2.Driver'
  jpa:
    show-sql: false
    properties:
      hibernate:
        format_sql: false
  hikari:
    pool-name: '${spring.datasource.username}'
    connection-timeout: 15000
    minimum-idle: 10
    maximum-pool-size: 30
    leak-detection-threshold: 15000
    connection-init-sql: 'SELECT 1 From Dual'
  h2:
    console:
      enabled: true
      path: /h2-console
